package gui;

import controllers.FishController;
import gui.custom.SqlComboBox;
import models.gui.comboBox.FishComboBoxModel;
import models.sql.Fish;
import models.sql.FishCatch;
import unit.IUniversalForm;

import javax.swing.*;
import java.awt.*;

public class FishCatchForm extends JPanel implements IUniversalForm<FishCatch> {
    private JPanel rootPanel;
    private JComboBox fishNameCB;
    private JTextField weightTxt;
    private JTextField voyageIdTxt;

    private FishController fishController;

    public FishCatchForm() {
        super();
        add(rootPanel);
    }

    public FishCatchForm(FishController fishController) {
        this();
        this.fishController = fishController;

        fishNameCB.setModel(new FishComboBoxModel(fishController));
    }

    @Override
    public FishCatch getRecord() {
        return new FishCatch(getVoyageId(), getFishId(), getWeight());
    }

    @Override
    public FishCatch getRawRecord() {
        FishCatch raw = new FishCatch();

        if (canGetFishId())
            raw.setFishId(getFishId());
        if (canGetWeight())
            raw.setWeight(getWeight());

        return raw;
    }

    @Override
    public void setRecord(FishCatch record) {
        voyageIdTxt.setText(String.valueOf(record.getVoyageId()));

        ComboBoxModel cb = new FishComboBoxModel(fishController);
        cb.setSelectedItem(record.getFishId());
        fishNameCB.setModel(cb);

        weightTxt.setText(String.valueOf(record.getWeight()));
    }

    @Override
    public Boolean[] canGets() {
        return new Boolean[]{canGetVoyageId(), canGetFishId(), canGetWeight()};
    }

    public boolean canGetFishId() {
        try {
            if (getFishId() != -1) {
                return true;
            } else {
                return false;
            }
        } catch (Throwable t) {
            return false;
        }
    }

    public boolean canGetWeight() {
        try {
            getWeight();
            return true;
        } catch (Throwable t) {
            return false;
        }
    }

    public boolean canGetVoyageId() {
        try {
            getVoyageId();
            return true;
        } catch (Throwable t) {
            return false;
        }
    }

    public int getVoyageId() {
        return Integer.parseInt(voyageIdTxt.getText());
    }


    protected Fish getFish() {
        return (Fish) fishNameCB.getSelectedItem();
    }

    public int getFishId() {
        return getFish().getId();
    }

    public int getWeight() {
        return Integer.parseInt(weightTxt.getText());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("fish name");
        rootPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(62, 167), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("weight");
        rootPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        weightTxt = new JTextField();
        rootPanel.add(weightTxt, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        fishNameCB = new SqlComboBox();
        rootPanel.add(fishNameCB, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("voyage Id:");
        label3.setVisible(false);
        rootPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        voyageIdTxt = new JTextField();
        voyageIdTxt.setText("");
        voyageIdTxt.setVisible(false);
        rootPanel.add(voyageIdTxt, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
