package gui;

import models.sql.Fish;
import unit.IUniversalForm;

import javax.swing.*;
import java.awt.*;

public class FishForm extends JPanel implements IUniversalForm<Fish> {
    private JPanel rootPanel;
    private JTextField nameTxt;
    private JTextField priceTxt;

    public FishForm() {
        super();
        add(rootPanel);
    }

    @Override
    public Fish getRecord() {
        return new Fish(getName(), getPrice());
    }

    @Override
    public Fish getRawRecord() {
        Fish rawFish = new Fish();
        if (canGetName()) {
            rawFish.setName(getName());
        }
        if (canGetPrice()) {
            rawFish.setPrice(getPrice());
        }
        return rawFish;
    }


    @Override
    public void setRecord(Fish record) {
        nameTxt.setText(record.getName());
        priceTxt.setText(Integer.toString(record.getPrice()));
    }

    public String getName() {
        return nameTxt.getText();
    }

    public Integer getPrice() {
        return Integer.parseUnsignedInt(priceTxt.getText());
    }

    public boolean canGetName() {
        return getName().length() != 0;
    }

    public boolean canGetPrice() {
        try {
            Integer.parseUnsignedInt(priceTxt.getText());
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }


    @Override
    public Boolean[] canGets() {
        return new Boolean[]{canGetName(), canGetPrice()};
    }

    public String incorrectFields() {
        String s = "";

        if (!canGetName())
            s += " name";
        if (!canGetPrice())
            s += " price";

        return s;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("name: ");
        rootPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("price");
        rootPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameTxt = new JTextField();
        nameTxt.setText("");
        rootPanel.add(nameTxt, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        priceTxt = new JTextField();
        priceTxt.setText("");
        rootPanel.add(priceTxt, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}