package gui;

import models.sql.Inventory;
import unit.IUniversalForm;

import javax.swing.*;
import java.awt.*;

public class InventoryForm extends JPanel implements IUniversalForm<Inventory> {
    private JPanel rootPanel;
    private JTextField nameTxt;
    private JTextField lifeTimeTxt;
    private JTextField manufactureDateTxt;

    public InventoryForm() {
        super();
        add(rootPanel);
    }

    @Override
    public Inventory getRecord() {
        return new Inventory(getName(), getLifeTime(), getManufactureDate());
    }

    @Override
    public Inventory getRawRecord() {
        Inventory inventory = new Inventory();

        if (canGetName())
            inventory.setName(getName());
        if (canGetLifeTime())
            inventory.setLifeTime(getLifeTime());
        if (canGetManufactureDate())
            inventory.setManufactureDate(getManufactureDate());

        return inventory;
    }

    @Override
    public void setRecord(Inventory record) {
        nameTxt.setText(record.getName());
        lifeTimeTxt.setText(Integer.toString(record.getLifeTime()));
        manufactureDateTxt.setText(Integer.toString(record.getManufactureDate()));
    }

    @Override
    public Boolean[] canGets() {
        return new Boolean[]{canGetName(), canGetLifeTime(), canGetManufactureDate()};
    }

    public boolean canGetName() {
        return getName().length() > 0 && getName().length() < 45;
    }

    public boolean canGetLifeTime() {
        try {
            getLifeTime();
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    public boolean canGetManufactureDate() {
        try {
            getManufactureDate();
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    public String getName() {
        return nameTxt.getText();
    }

    public int getLifeTime() {
        return Integer.parseUnsignedInt(lifeTimeTxt.getText());
    }

    public int getManufactureDate() {
        return Integer.parseUnsignedInt(manufactureDateTxt.getText());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("name");
        rootPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("life time");
        rootPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("manufacture date");
        rootPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameTxt = new JTextField();
        rootPanel.add(nameTxt, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lifeTimeTxt = new JTextField();
        rootPanel.add(lifeTimeTxt, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        manufactureDateTxt = new JTextField();
        rootPanel.add(manufactureDateTxt, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
