package gui;

import models.sql.Ship;
import unit.IUniversalForm;

import javax.swing.*;
import java.awt.*;

public class ShipForm extends JPanel implements IUniversalForm<Ship> {
    private JPanel rootPanel;
    private JTextField nameTxt;

    public ShipForm() {
        super();
        add(rootPanel);
    }

    @Override
    public Ship getRecord() {
        return new Ship(getName());
    }

    @Override
    public Ship getRawRecord() {
        Ship rawShip = new Ship();
        if (canGetName())
            rawShip.setName(getName());
        return rawShip;
    }

    @Override
    public void setRecord(Ship record) {
        nameTxt.setText(record.getName());
    }

    @Override
    public Boolean[] canGets() {
        return new Boolean[]{canGetName()};
    }

    public String getName() {
        return nameTxt.getText();
    }

    public boolean canGetName() {
        return getName().length() != 0;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("name");
        rootPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameTxt = new JTextField();
        rootPanel.add(nameTxt, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
