package gui;

import controllers.InventoryController;
import gui.custom.SqlComboBox;
import models.gui.comboBox.InventoryComboBoxModel;
import models.sql.Inventory;
import models.sql.VoyageInventory;
import unit.IUniversalForm;

import javax.swing.*;
import java.awt.*;

public class VoyageInventoryForm extends JPanel implements IUniversalForm<VoyageInventory> {
    private JPanel rootPanel;
    private JTextField voyageIdTxt;
    private SqlComboBox inventoryNameCB;

    private InventoryController controller;

    public VoyageInventoryForm() {
        super();
        add(rootPanel);
    }

    public VoyageInventoryForm(InventoryController controller) {
        this();
        this.controller = controller;

        inventoryNameCB.setModel(new InventoryComboBoxModel(controller));
    }

    @Override
    public VoyageInventory getRecord() {
        return new VoyageInventory(getVoyageId(), getInventoryId());
    }

    @Override
    public VoyageInventory getRawRecord() {
        VoyageInventory vi = new VoyageInventory();

        if (canGetVoyageId())
            vi.setVoyageId(getVoyageId());
        if (canGetInventoryId())
            vi.setInventoryId(getInventoryId());

        return vi;
    }

    @Override
    public void setRecord(VoyageInventory record) {
        voyageIdTxt.setText(String.valueOf(record.getVoyageId()));

        ComboBoxModel cb = new InventoryComboBoxModel(controller);
        cb.setSelectedItem(record.getInventoryId());
        inventoryNameCB.setModel(cb);
    }

    @Override
    public Boolean[] canGets() {
        return new Boolean[]{canGetVoyageId(), canGetInventoryId()};
    }

    public boolean canGetVoyageId() {
        try {
            if (getVoyageId() != -1) {
                return true;
            } else return false;
        } catch (Throwable t) {
            return false;
        }
    }

    public boolean canGetInventoryId() {
        try {
            if (getInventoryId() != -1) {
                return true;
            } else return false;
        } catch (Throwable t) {
            return false;
        }
    }

    public int getVoyageId() {
        return Integer.parseInt(voyageIdTxt.getText());
    }

    public int getInventoryId() {
        return getInventory().getId();
    }

    protected Inventory getInventory() {
        return (Inventory) inventoryNameCB.getSelectedItem();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("voyage:");
        label1.setVisible(false);
        rootPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("inventory:");
        rootPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        voyageIdTxt = new JTextField();
        voyageIdTxt.setVisible(false);
        rootPanel.add(voyageIdTxt, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        inventoryNameCB = new SqlComboBox();
        rootPanel.add(inventoryNameCB, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
